apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-dp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
      - name: task-manager-api
        image: devtfo/task-manager:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            value: "mongodb://task-manager-db-service:27017/"
          - name: DATABASE_USER
            value: root
          - name: DATABASE_PASSWORD
            value: 12344321
          - name: TOKEN_JWT
            value: 12344321
