apiVersion: v1
kind: Pod
metadata:
  name: task-manager-db
  labels:
    app: task-manager-db
spec:
  containers:
  - name: task-manager-db
    image: mongo
    ports:
      - containerPort: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: root
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: 12344321
